// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUzxog7MkxPfQmLZtq_bUTUIyHRUN3jw',
    appId: '1:968351582880:web:9e869c18b69803df6057c5',
    messagingSenderId: '968351582880',
    projectId: 'chirp-607b8',
    authDomain: 'chirp-607b8.firebaseapp.com',
    storageBucket: 'chirp-607b8.appspot.com',
    measurementId: 'G-FGLXB3S7NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE_-cjQXp-4w78_4L4uoH9aDuLaVxXY4Q',
    appId: '1:968351582880:android:a1019c446624a8c76057c5',
    messagingSenderId: '968351582880',
    projectId: 'chirp-607b8',
    storageBucket: 'chirp-607b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYayJxABdOm-IudIWKK8PxWoZrwe3OaU4',
    appId: '1:968351582880:ios:4bd558ba9ae2c5ff6057c5',
    messagingSenderId: '968351582880',
    projectId: 'chirp-607b8',
    storageBucket: 'chirp-607b8.appspot.com',
    iosClientId: '968351582880-j77ne4pocbccmpmngr7s86g0anect8va.apps.googleusercontent.com',
    iosBundleId: 'com.example.chirp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYayJxABdOm-IudIWKK8PxWoZrwe3OaU4',
    appId: '1:968351582880:ios:4bd558ba9ae2c5ff6057c5',
    messagingSenderId: '968351582880',
    projectId: 'chirp-607b8',
    storageBucket: 'chirp-607b8.appspot.com',
    iosClientId: '968351582880-j77ne4pocbccmpmngr7s86g0anect8va.apps.googleusercontent.com',
    iosBundleId: 'com.example.chirp',
  );
}
